name: Update Main Page (mfg-b)
on: [push]

jobs:
  update-submodule-on-mfg-b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          repository: mateusfg7/mfg-b
          token: ${{ secrets.PAT }}
          submodules: recursive


      - name: Config Git
        run: |
          git config --global user.email "mateusfelipefg77@gmail.com"
          git config --global user.name "mateusfg7"
      - name: Update remotly submodules
        run: git submodule update --remote _mybrainknowledge
      
      - name: Add and commit changed files
        run: |
          git commit -a -m "Update _mybrainknowledge"
      
      - name: Push changes
        run: git push
